---
- hosts: all
  become: yes
  tasks:
  - name: Install packages
    apt:
      name:
      - nmap
      state: latest
  - name: Scan host using nmap
    shell: nmap "{{ 10.0.0.100 }}"
    register: out

  - debug: var=out.stdout_lines
